<?php

namespace AppBundle\Repository;

use \Doctrine\ORM\Query;

/**
 * car_serviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarServiceRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllServicesByCarPlateNumber($carPlateNumber) {
        $query = $this->getEntityManager()
                      ->createQuery(
                        'SELECT c, cs FROM AppBundle:CarService cs 
                        JOIN cs.car c 
                        WHERE c.plateNumber = :plate'
                        )->setParameter('plate', $carPlateNumber);
       

       try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
