<?php

namespace AppBundle\Repository;

/**
 * ProduseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllProduseByCategorie($categorieTitlu) {
        $query = $this->getEntityManager()
                      ->createQuery(
                        'SELECT c, p FROM AppBundle:Produse p
                            JOIN p.categorie c
                            WHERE c.titlu = :titlu'
                        )->setParameter('titlu', $categorieTitlu);
       

       try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
