app:
    resource: '@AppBundle/Controller/'
    type: annotation
car:
    path:     /car
    defaults: { _controller: AppBundle:Car:car }  
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
