security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
 
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
 
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
 
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                
               
            logout:       true    
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 2678400 # 1 month in seconds
                path:     /
 
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/car/, role: ROLE_USER }
        - { path: ^/car/add/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/car/service, role: ROLE_USER }
        - { path: ^/car/service/add/, role: ROLE_ADMIN }
        - { path: ^/form/, role: ROLE_USER }